"""Abstractions for the service layer (Dependency Inversion Principle).

Controllers depend on these protocols rather than concrete implementations,
making it possible to swap backends or mock for testing.
"""

from typing import Protocol, Optional


class DataServiceProtocol(Protocol):
    """Protocol defining the contract for the data access layer."""

    # User operations
    def create_user(self, **kwargs) -> int: ...
    def authenticate(self, username: str, password: str): ...
    def get_user_by_id(self, user_id: int): ...
    def get_users_by_role(self, role: str) -> list: ...
    def get_learners_by_mentor(self, mentor_id: int) -> list: ...
    def update_user_accessibility(self, user_id: int, prefs: dict) -> None: ...
    def update_user_stem_interests(self, user_id: int, interests: list) -> None: ...
    def update_educator_expertise(self, user_id: int, areas: list) -> None: ...
    def has_users(self) -> bool: ...

    # Learning path operations
    def create_learning_path(self, title: str, description: str,
                             category: str, created_by: int) -> int: ...
    def get_all_learning_paths(self) -> list: ...
    def get_learning_path_by_id(self, path_id: int): ...
    def get_paths_by_educator(self, educator_id: int) -> list: ...
    def update_learning_path(self, path_id: int, title: str,
                             description: str, category: str) -> None: ...
    def delete_learning_path(self, path_id: int) -> None: ...

    # Course operations
    def create_course(self, title: str, description: str, path_id: int,
                      created_by: int, order_index: int = 0) -> int: ...
    def get_courses_by_path(self, path_id: int) -> list: ...
    def update_course(self, course_id: int, title: str,
                      description: str) -> None: ...
    def delete_course(self, course_id: int) -> None: ...

    # Content operations
    def create_content(self, title: str, text_body: str, course_id: int,
                       created_by: int, order_index: int = 0) -> int: ...
    def get_contents_by_course(self, course_id: int) -> list: ...
    def update_content(self, content_id: int, title: str,
                       text_body: str) -> None: ...
    def delete_content(self, content_id: int) -> None: ...

    # Assignment operations
    def create_assignment(self, mentor_id: int, learner_id: int, path_id: int,
                          excluded_course_ids=None,
                          assigned_date: str = "") -> int: ...
    def get_assignments_by_learner(self, learner_id: int) -> list: ...
    def get_assignments_by_mentor(self, mentor_id: int) -> list: ...

    # Progress operations
    def mark_course_completed(self, learner_id: int, assignment_id: int,
                              course_id: int,
                              completed_date: str = "") -> None: ...
    def get_progress_for_assignment(self, assignment_id: int) -> tuple: ...
    def get_progress_records(self, assignment_id: int) -> list: ...
    def is_course_completed(self, learner_id: int, assignment_id: int,
                            course_id: int) -> bool: ...

    # Opportunity operations
    def create_opportunity(self, title: str, description: str, opp_type: str,
                           posted_by: int,
                           posted_date: str = "") -> int: ...
    def get_all_opportunities(self) -> list: ...
